<a href="https://colab.research.google.com/github/mopurivasu/Webclubtasks/blob/main/ybi_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import load_digits
df=load_digits()

In [ ]:
df.images.shape

(1797, 8, 8)

In [ ]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

# New Section

In [ ]:
df.images[0].shape

(8, 8)

In [ ]:
len(df.images)

1797

In [ ]:
n_samples=len(df.images)
data=df.images.reshape(n_samples,-1)

In [ ]:
data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [ ]:
data[0].shape

(64,)

In [ ]:
data.shape

(1797, 64)

In [ ]:
data.min()

0.0

In [ ]:
data.max()

16.0

In [ ]:
data=data/16

In [ ]:
data.min()

0.0

In [ ]:
data.max()

1.0

In [ ]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,df.target,test_size=0.3)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=rf.predict(x_test)
y_pred

array([2, 6, 2, 2, 9, 3, 6, 4, 7, 8, 5, 3, 9, 9, 0, 3, 6, 5, 6, 5, 7, 6,
       3, 5, 9, 1, 3, 0, 7, 5, 2, 4, 3, 8, 8, 0, 9, 0, 3, 7, 5, 7, 2, 0,
       7, 4, 9, 3, 2, 9, 9, 2, 8, 1, 1, 0, 7, 9, 2, 9, 6, 4, 8, 1, 5, 4,
       6, 0, 7, 6, 5, 7, 0, 7, 1, 5, 9, 9, 3, 5, 7, 2, 9, 7, 2, 7, 6, 3,
       7, 8, 6, 2, 8, 4, 3, 0, 8, 7, 4, 0, 9, 7, 4, 2, 8, 1, 4, 6, 7, 2,
       9, 2, 0, 2, 9, 8, 2, 5, 0, 2, 4, 3, 0, 6, 0, 1, 3, 6, 4, 4, 4, 1,
       0, 9, 4, 2, 2, 0, 0, 4, 7, 1, 2, 5, 4, 5, 6, 3, 5, 0, 6, 1, 6, 3,
       8, 8, 6, 5, 7, 5, 5, 4, 9, 2, 4, 2, 7, 6, 1, 2, 1, 3, 4, 0, 9, 3,
       5, 8, 2, 9, 7, 2, 2, 4, 9, 9, 7, 6, 8, 4, 4, 4, 6, 4, 0, 0, 4, 0,
       1, 1, 8, 1, 4, 5, 8, 3, 2, 4, 9, 4, 8, 3, 1, 8, 4, 6, 3, 7, 7, 9,
       1, 8, 1, 5, 1, 2, 9, 3, 0, 6, 4, 9, 9, 1, 5, 9, 8, 0, 8, 7, 9, 5,
       6, 2, 8, 6, 0, 5, 6, 4, 3, 5, 1, 7, 5, 0, 2, 9, 0, 9, 6, 2, 2, 3,
       6, 3, 1, 2, 1, 8, 9, 6, 0, 3, 3, 4, 9, 2, 7, 7, 1, 2, 9, 5, 7, 0,
       4, 5, 3, 7, 4, 7, 7, 8, 9, 0, 0, 1, 3, 5, 9,

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_pred)

array([[51,  0,  0,  0,  2,  0,  0,  0,  0,  0],
       [ 0, 51,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 54,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 49,  0,  1,  0,  0,  2,  0],
       [ 0,  0,  0,  0, 61,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 51,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0, 51,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 62,  0,  0],
       [ 0,  2,  0,  0,  1,  0,  0,  1, 45,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0, 53]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        53
           1       0.96      1.00      0.98        51
           2       1.00      1.00      1.00        54
           3       0.98      0.94      0.96        52
           4       0.94      0.98      0.96        62
           5       0.98      1.00      0.99        51
           6       1.00      0.98      0.99        52
           7       0.97      1.00      0.98        62
           8       0.96      0.92      0.94        49
           9       1.00      0.98      0.99        54

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

